wallet/main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('wallets/', views.WalletListView.as_view(), name='wallets'),
    path('wallets/<int:pk>/', views.WalletDetailView.as_view(), name='wallet_detail'),
    path('wallets/<int:pk>/edit', views.WalletUpdaitView.as_view(), name='wallet_edit'),
    path('wallets/<int:pk>/delete', views.WalletDeleteView.as_view(), name='wallet_del'),
    path('wallets/add', views.WalletCreateView.as_view(), name='wallet_add'),
    path('transactions/', views.TransactionListView.as_view(), name='transactions'),
    path('transactions/add', views.TransactionCreateView.as_view(), name='transaction_add'),
    path('transactions/<int:pk>/delete', views.TransactionDeleteView.as_view(), name='transaction_del'),
]

wallet/wallet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

]

wallet/main/models.py
from django.db import models


class Wallet(models.Model):
    """Модель Кошелёк.

    Название -- Произвольное название для кошелька/счета.

    Баланс -- Поле отображающее остаток в кошельке/на счете,
    по умолчанию 0, не может редактироваться на прямую, только
    через транзакции.
    """
    name = models.CharField(verbose_name="Название", max_length=250)
    balance = models.DecimalField(
        verbose_name="Баланс",
        max_digits=11,
        decimal_places=2,
        default=0
    )

    def __str__(self):
        return self.name


class Transactions(models.Model):
    """Модель Транзакции.

    Кошелёк -- поле для указания кошелька к которому относится транзакция,
    используется для фильтрации при выводе истории транзакций по кошельку,
    и при создании транзакции.

    Сумма -- поле для указания суммы пополнения либо списания.

    Тип транзакции -- вполе для выбора типа транзакции "Пополнение" или
    "Списание", по умолчанию - "Списание".

    Описание -- поле для краткого описания транзакции, обязательное
    для заполнения.

    Дата -- при создании транзакции дата заполняется автоматически.
    """
    wallet = models.ForeignKey(
        Wallet,
        on_delete=models.CASCADE,
        verbose_name="Кошелёк"
    )
    amount = models.DecimalField(
        verbose_name="Сумма",
        max_digits=11,
        decimal_places=2,
    )
    transaction_type = models.CharField(
        verbose_name="Тип транзакции",
        max_length=5,
        choices=[('plus', 'Пополнение'), ('minus', 'Списание')],
        default='minus',
    )
    description = models.CharField(
        verbose_name="Описание",
        max_length=300,
        blank=False,
    )
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.description

wallet/main/forms.py
from django.forms import ModelForm
from .models import Wallet, Transactions


class WalletForm(ModelForm):

    class Meta:
        model = Wallet
        fields = (
            'name',
        )


class TransactionsForm(ModelForm):

    class Meta:
        model = Transactions
        fields = (
            'wallet',
            'amount',
            'transaction_type',
            'description',
        )

wallet/main/views.py
from django.views import generic
from .models import Wallet, Transactions
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import WalletForm, TransactionsForm
from django.http import HttpResponseRedirect, HttpResponse


class WalletListView(LoginRequiredMixin, generic.ListView):
    """Полный список кошельков.
    """
    model = Wallet
    template_name = 'main/wallets.html'


class WalletDetailView(LoginRequiredMixin, generic.DetailView):
    """Страница кошелька
    """
    model = Wallet
    template_name = 'main/wallet.html'

    def get_context_data(self, **kwargs):
        obj = self.object
        context = super(WalletDetailView, self).get_context_data(**kwargs)
        context['transactions'] = Transactions.objects.filter(wallet=obj.id)
        return context


class WalletCreateView(LoginRequiredMixin, generic.CreateView):
    """Страница добавления кошелька
    """
    model = Wallet
    form_class = WalletForm
    success_url = '/wallets'


class WalletUpdaitView(LoginRequiredMixin, generic.UpdateView):
    """Страница редактирования кошелька
    """
    model = Wallet
    form_class = WalletForm
    template_name = 'main/wallet_edit.html'
    success_url = '/wallets'


class WalletDeleteView(LoginRequiredMixin, generic.DeleteView):
    """Страница удаления кошелька
    """
    model = Wallet
    template_name = 'main/wallet_del.html'
    success_url = '/wallets'


class TransactionListView(LoginRequiredMixin, generic.ListView):
    """Страница истории всех транзакций
    """
    model = Transactions
    template_name = 'main/transactions.html'


class TransactionCreateView(LoginRequiredMixin, generic.CreateView):
    """Страница создания транзакции
    """
    model = Transactions
    form_class = TransactionsForm
    success_url = '/wallets'

    def form_valid(self, form):
        obj = form.instance
        wallet = Wallet.objects.get(name=obj.wallet)
        if obj.transaction_type == 'plus':
            wallet.balance += obj.amount
            wallet.save()
            self.object = form.save()
        else:
            if obj.amount > wallet.balance:
                return HttpResponse('<h1>На счете кошелька недостаточно средств!</h1>')
            else:
                wallet.balance -= obj.amount
                wallet.save()
                self.object = form.save()
        return HttpResponseRedirect('/wallets')


class TransactionDeleteView(LoginRequiredMixin, generic.DeleteView):
    """Страница удаления транзакции
    """
    model = Transactions
    template_name = 'main/transaction_del.html'
    success_url = '/wallets'

wallet/main/templates/main/base.html
{% load static %}


<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href=https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/style.css' %}">

    <style>
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            {% if user.is_authenticated %}
            <a class="nav-link">Привет, {{ user.username }}!</a>
            <a class="navbar-brand text-muted" href="{% url 'logout' %}"><small>Выйти</small></a>
            {% else %}
            <a class="navbar-brand" href="{% url 'login' %}">Войти</a>
            {% endif %}
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'wallets' %}">Главная<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'transaction_add' %}">Пополнить/списать<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'wallet_add' %}">Создать новый кошлёк<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'transactions' %}">История операций<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid" >
        <div class="starter-template">
            <h1>
                {% block header %}{% endblock %}
            </h1>
        </div>
        <div class="row">
            <main class="col-md-10">
                          {% block content %}
                          {% endblock %}
            </main>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>

</html>

wallet/main/templates/main/transaction_del.html
{% extends 'main/base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Вы действительно хотите удалить транзакцию?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

wallet/main/templates/main/transactions.html
{% extends 'main/base.html' %}

{% block title %}
Transactions
{% endblock %}

{% block content %}
    <h1>История операций</h1>
    <ul>
      {% for trans in transactions_list %}
      <li>
        <p>Кошелёк:{{ trans.wallet }}, сумма:{{ trans.amount }} руб., вид операции: {% if trans.transaction_type == 'plus' %}Пополнение{% else %}Списание{% endif %}, дата:{{ trans.date }}, комментарий:{{ trans.description }}.</p>
      </li>
      {% endfor %}
    </ul>

{% endblock %}

wallet/main/templates/main/transactions_form.html
{% extends 'main/base.html' %}

{% block content %}
    <h1>Новая операция</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Подтвердить операцию">
    </form>
{% endblock content %}

wallet/main/templates/main/wallet.html
{% extends 'main/base.html' %}

{% block title %}
WALLET {{ wallet.name }}
{% endblock %}

{% block content %}
    <h1>{{ wallet.name }}</h1>
    <h3>{{ wallet.balance }} руб.</h3>
    <hr>
    <h4>История операций по кошельку:</h4>
    <ul>
      {% for trans in transactions %}
      <li>
          <p>Вид операции:{% if trans.transaction_type == 'plus' %}Пополнение{% else %}Списание{% endif %}, сумма: {{ trans.amount }} руб., дата: {{ trans.date }}, комментарий: {{ trans.description }}.  <a href="{% url 'transaction_del' pk=trans.id %}">Удалить транзакцию из истории</a></p>
      </li>
      {% endfor %}
    </ul>
    <a href="{% url 'wallet_edit' pk=wallet.id%}">Редактировать/удалить кошелёк</a>
{% endblock %}

wallet/main/templates/main/wallet_del.html
{% extends 'main/base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Вы действительно хотите удалить "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

wallet/main/templates/main/wallet_edit.html
{% extends 'main/base.html' %}

{% block content %}
    <h1>Редактировать кошелёк</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Изменить">
    </form>
    <a href="{% url 'wallet_del' pk=wallet.id %}">Удалить кошелёк</a>
{% endblock content %}

wallet/main/templates/main/wallet_form.html
{% extends 'main/base.html' %}

{% block content %}
    <h1>Создайте новый кошелёк</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Создать кошелёк">
    </form>
{% endblock content %}

wallet/main/templates/main/wallets.html
{% extends 'main/base.html' %}

{% block title %}
WALLETS
{% endblock %}

{% block content %}
    <h1>Список кошельков</h1>
    <ul>
      {% for wallet in wallet_list %}
      <li>
        <a href="{{ wallet.pk }}">{{ wallet.name }}</a>
          <h3>{{ wallet.balance }} руб.</h3>
      </li>
      {% endfor %}
    </ul>

{% endblock %}